---
title: "Worksheet demo 1"
author: "Liam Mueller"
date: "9/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(error = TRUE)
```

Answer the following questions by typing the appropriate code in the code boxes (denoted by ``` signs). Each line of code that you are responsible for will already have a <- arrow. Leave the following line as it is, that line will show me the console output in the final document. When you have answered all of the questions, double-check your work, be sure the author line above contains your full name 

  (for example: author: "Liam Mueller" ) 

and finally hitting the Knit button above. Save the file with your name and the week number in the file name 

  (for example: "Liam_Mueller_1").  

\newpage

Questions:

1. Assign to a vector called X the values 1,3,5,6,7, and 9. Assign to a vector called Y the values 2,7,4,5,2 and 12.

```{r}
X<- c(1,3,5,6,7,9)
X
Y<- 
Y
```

\newpage

2. Concatenate (combine) the two vectors together as one larger vector called Z.
```{r}
Z <- 
  
Z  
```
\newpage

3. Create a new vector that includes all the values in Z that are less than 6.
```{r}
newZ<- 
newZ
```
\newpage

4. Using R functions, calculate the mean of Z.
```{r}
meanZ<-
meanZ
```
\newpage

5. Using R functions, calculate the length of X.
```{r}
lengthX<- 
```

